download:
  url: https://www.rs-aiot.com
  
ext:
  sigfox:
    cra:
      url: https://cra-staging.sigfox.com
      id: 616581a344e9d71c67301c80 
      user: 616598fae08a8a6f22d452ff 
      password: ad06c597447e0e8dcaf2e9b4e918e41b 
    api:
      url: https://api-staging.sigfox.com
      id: 61657ef7b45d535f2de23721 
      user: 61659869b45d535f2de239dc 
      password: ce1c6370051ca2fac1b81042e1bed262

#tanent 계정 정보
nap:
  id: ENC(7ug79ydBf2k6yXze6pID47KQy3THIKrr)
  pwd: ENC(4QTQ1+1kZ93Skc1jaQf0jg==)    
jwt: 
  nap:
    securiteKey: remotesolutionJwttokenSecuritykeyrsaiotcom #ENC(9R8FjBXinkcqhnTrSLKDy4AQMjGXjAC+xF+nUGGxjphHK7FRF2HowetkSsFbKSTep+WRbz6vSAA=)
    issuer: rs-aiot.com
    ttlMills: 86000 #60*60*24

rms:
  makername: RemoteSolutio      

spring:
  zipkin:
    base-url: https://log.rs-aiot.com

#Sap연결 정보
sap:
  #client: 110
  #host: 222.117.127.178
  client: 500 #TB
  host: 222.117.127.177 #TB
  language: KO
  systemnumber: 00
  user: RSCM01
  group: 
  password: 12345678
  #connection pool 설정
  pool:
    capacity: 5 #허용 pool 갯수
    limit: 5 #최대 허용 pool 갯
 
iamport:
  url: https://api.iamport.kr
  #url: http://localhost:8082
  api:
    key: 1094509009804392
    secret: BQtFw10whZVMwaxg4yac9djyWAQd5JOHzin6joDBoynUJUbNtl0CykbvV2J0LyIlQ5s9t6KRE8Mn2Ybv    

payment:
  limit:
    min: 100,0.1
    
contract:
  expiration: 7

#정기 배치 수동 처리할 최대 목록 개수로, 처리할 데이타가 1000000개 이면 해당 개수:10000 씩 100개 thread 병렬로 처리함 poolmax완 관련되어 있음
pg:
  list:
    count: 1000

user:
  permission:
    #entityGroupId: c1451110-d68b-11ec-9189-17045420bae6
    roleId: ad20a070-d67f-11ec-9189-17045420bae6
    attributeEntityId: 2c3a17e0-d682-11ec-9189-17045420bae6
    #tenantId: 3b3ca3c0-d5a6-11ec-9d65-4bd164c0396c
    genericRoleId: 3c6a4e50-d5a6-11ec-9d65-4bd164c0396c    
       