server:
  port: ${port:8081}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true # 유레카 클라이언트 활성화
    register-with-eureka: true # 유레카 클라이언트 활성화
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/} # 유레카 클라이언트로 등록 

logging:
  config: ${user.home}/core/logback-spring.xml
  level:
    reactor:
      netty: INFO      

authexclude: 
  endpoint: /api/nap,/api/auth/login,/api/sap,/api/paypal,/api/stripe

napAuthexclude: 
  endpoint: /api/nap/event/boot,/api/nap/event/token

management:
  endpoints:
    web:
      exposure:
        include: gateway,health
  endpoint: 
    gateway:
      enabled: false   
spring:    
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sample:
    zipkin:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: apiservice-front
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/ui/**,/api/batch/**,/api/payment/**,/api/sap/**
          filters:
            #- RewritePath=/api/(?<path>.*),$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            - name: AuthFilter
              args:
#                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
        - id: api-batch-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/batch/**    
        - id: apiservice-nap
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-NAP
          predicates:
            - Path=/api/nap/**
          filters:
            #-- RewritePath=/api/front/(?<path>.*),$\{path}
            - name: NapFilter
              args:
                baseMessage: Spring Cloud Gateway NapFilter
                preLogger: true
                postLogger: true
        - id: api-ext-pg-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/payment/**
        - id: api-sap-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/sap/**
        - id: common-auth
          uri: https://dev.rs-aiot.com
          predicates:
            - Path=/api/auth/**,/api/v1/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: api-test-svc
          uri: http://localhost:8082/
          predicates:
            - Path=/api/test/**  