spring:
  application:
    name: gateway
  profiles:
    active: ${profile:prod}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: https://prod-log.rs-aiot.com
    enabled: true
  sample:
    zipkin:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: api-front-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/ui/**
          filters:
            #- RewritePath=/api/(?<path>.*),$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            - name: AuthFilter
              args:
#                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
        - id: api-batch-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/batch/**    
        - id: api-nap-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-NAP
          predicates:
            - Path=/api/nap/**
          filters:
            #-- RewritePath=/api/front/(?<path>.*),$\{path}
            - name: NapFilter
              args:
                baseMessage: Spring Cloud Gateway NapFilter
                preLogger: true
                postLogger: true
        - id: api-ext-pg-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/payment/**
        - id: api-sap-svc
          #uri: http://localhost:8082/
          uri: lb://APISERVICE-FRONT
          predicates:
            - Path=/api/sap/**
        - id: common-auth
          uri: https://www.rs-aiot.com
          predicates:
            - Path=/api/auth/**,/api/v1/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: api-test-svc
          uri: http://localhost:8082/
          predicates:
            - Path=/api/test/**  